version: 2.1

parameters:
  branch-param:
    type: string
    default: master

  branch-set:
    type: boolean
    default: false

jobs:
  build:
    docker:
      - image: cimg/node:14.12.0-browsers
    steps:
      - checkout
      - run:
          name: Set branch associated with tag
          command: |
            if [[ -v CIRCLE_TAG ]] && [[ << pipeline.parameters.branch-set >> == false ]]; then
              sha1=$(git rev-parse tags/$CIRCLE_TAG~0)
              BRANCH=$(git branch -a --contains $sha1 | grep "remotes/origin" | cut -d '/' -f 3)
              curl --location --request POST "https://circleci.com/api/v2/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pipeline" \
              --header 'Content-Type: application/json' \
              -u "${API_TOKEN}:" \
              --data-raw "{\"tag\": \"${CIRCLE_TAG}\", \"parameters\": { \"branch-param\": \"${BRANCH}\", \"branch-set\": true}}"
              circleci-agent step halt
            fi
      - when:
          condition:
            not:
              equal: [ master, << pipeline.parameters.branch-param >> ]
          steps:
            - run: echo "Not on master"
      - when:
          condition:
            equal: [ master, << pipeline.parameters.branch-param >> ]
          steps:
            - run: echo "Skipping e2e on master"

workflows:
  test2:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
